name: 'Create a LLM generated README.md with (Azure) OpenAI'
description: "Create a README.md file by analyzing repository functions using (Azure) OpenAI and ChatGPT."
inputs:
  github_token:
    description: 'GitHub token for authentication.'
    required: true
  openai_api_key:
    description: 'API key for OpenAI services.'
    required: true
  azure_openai_api_key:
    description: 'API key for Azure OpenAI services.'
    required: true
  openai_model:
    description: 'OpenAI model for chat/completions endpoint.'
    required: false
    default: 'gpt-4o-mini'
  azure_openai_endpoint:
    description: 'Azure OpenAI endpoint URL.'
    required: false
    default: ''
  azure_openai_version:
    description: 'Azure OpenAI API version.'
    required: false
    default: ''
  max_tokens:
    description: 'Max number of tokens for the prompt.'
    required: false
    default: '1000'
  temperature:
    description: 'Model creativity level (higher = more creative).'
    required: false
    default: '0.6'
  sample_prompt:
    description: 'Sample prompt for the model (see SAMPLE_PROMPT in Python).'
    required: false
    default: ''
  sample_response:
    description: 'Ideal response sample for the sample prompt.'
    required: false
    default: ''
  completion_prompt:
    description: 'Final prompt for the model (see COMPLETION_PROMPT in Python).'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cpu'
  color: 'green'
