name: Generate/update README

on:
  workflow_dispatch: 

jobs:
  openai-pr-description:
    runs-on: ubuntu-22.04

    steps:  
      - uses: actions/checkout@v4
      - name: Generate/update README file
        uses: ./
        with:
          github_token: ${{ secrets.TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          azure_openai_version: ${{ secrets.AZURE_OPENAI_VERSION }}